# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Counter App CI

on:
  push:
    branches: [ "master" ]
    

jobs:
  build:

    runs-on: self-hosted

    steps: 
    - name: Checkout repository 
      uses: actions/checkout@v2 
      
    - name: Set up Node.js 
      uses: actions/setup-node@v2 
      with:
        node-version: '14' # specify your Node.js version 
        
    - name: Install dependencies 
      run: npm install 
      
    - name: Build project 
      run: npm run build # or your specific build command
    

    - run: tar -czf build.tar.gz build

    - name: Upload build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: build.tar.gz


  deploy:
    needs: build
    runs-on: self-hosted

    steps: 
      - name: Checkout repository
        uses: actions/Checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: build/

      - name: Deploy via SSH 
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          
          scp -i ~/.ssh/id_rsa -P ${{ secrets.SSH_PORT }} build/build.tar.gz ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/ec2-user/counter-app

          ssh -i ~/.ssh/id_rsa -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /home/ec2-user/counter-app
            rm -rf *.html *.js *.css static *.json *.ico
            tar -xzf build.tar.gz
            mv build/* .
            rm -rf build build.tar.gz
          EOF
0
